name: Run SuperLearner
run-name: Run SuperLearner workflow ${{ github.event.inputs.workflow-name }} as user ${{ github.event.inputs.pw-user }}
on:
  #------------------------------------------------------------
  # We previously launched the workflow on release. However,
  # a releas/tag is a static thing and points only to the state
  # of the repository BEFORE the machine learning runs (i.e.
  # when the new input data is uploaded to start the ML
  # workflow) so the release itself did not have a snapshot 
  # of the final result (the ML models and their outputs).
  #release:
  #  types: [published]
  #------------------------------------------------------------
  # Instead, launch workflow anytime a push, on any branch, that
  # modifies a file in input_data matching the pattern of the core 
  # input files, ICON-ModEx_*.csv. Note that these files are NOT
  # changed by the machine learning workflow when it makes a push
  # back to GitHub so we don't end up in an infinite loop of
  # push-launches.
  push:
    paths:
      - 'input_data/ICON-ModEx_*.csv'

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    name: modex-iteration-cloud-pw
    env:
      PW_PLATFORM_HOST: 'activate.parallel.works'
      PW_API_KEY: ${{ secrets.PW_API_KEY }}

    steps:
      - name: Install PW CLI
        # See more installation instructions at https://parallelworks.com/docs/cli
        # To keep environment changes persistent step to step, must write to special
        # file $GITHUB_ENV.
        run: |
          mkdir -p ~/bin
          wget "https://activate.parallel.works/cli/pw-linux-amd64" -O ~/bin/pw
          chmod u+x ~/bin/pw
          echo "PATH=${PATH}:~/bin" >> $GITHUB_ENV
      - name: Authenticate to PW CLI
        run: |
          pw auth apikey "${PW_API_KEY}"
          pw auth whoami
      - name: Get Workflow
        # We are going to use the workflow.yaml
        # which defines the SuperLearner workflow
        # directly from its repository and run it
        # "inline" on ACTIVATE in the next step.
        # An inline run means the SuperLearner
        # workflow does not need to be added to 
        # the user's ACTIVATE account in advance;
        # the workflow definition is grabbed on-the-fly
        # and based on the local state on this GitHub
        # runner.
        run: |
          git clone https://github.com/parallelworks/sl_core
          pwd
          ls -alh
      - name: Launch workflow
        # PW CLI-based launch
        # Use folded style (>) for this long single command instead
        # of literal style (|).
        #-----------------------------------
        # The launching process, pw workflow run,
        # will exit as soon as the workflow is running
        # when it is used non-interactively. (When
        # used interactively, it takes over the terminal
        # so the user can browse progress, but this
        # persistence does not happen in the GitHub
        # runner's context. Therefore, another step
        # is required to monitor for the completion
        # of the pw workflow-executor execute
        # process that is launched by pw workflow run.
        run: >
          pw workflow run ./sl_core/workflow.yaml -i '{
            "repositories": {
              "ml_arch_repo": "https://github.com/${{ github.repository }}",
              "ml_arch_branch": "${{ github.ref_name }}",
              "ml_arch_token": "${{ secrets.GITHUB_TOKEN }}",
              "push_to_gh": true,
              "ml_code_repo": "https://github.com/parallelworks/sl_core",
              "ml_data_repo": "https://github.com/parallelworks/global-river-databases"
            },
            "resources": {
              "whost": "pw://pwdemo.stefan/gce",
              "miniconda_loc": "/home/${USER}/.miniconda3",
              "my_env": "superlearner"
            },
            "superlearner": {
              "train_test_data": "scripts/prep_06_output_final_train.csv",
              "train_test_groups": "scripts/prep_06_output_final_gid.csv",
              "predict_data": "scripts/prep_06_output_final_predict",
              "num_inputs": 25,
              "superlearner_conf": "sample_inputs/superlearner_conf.py",
              "work_dir_base": "ml_models/sl_",
              "hpo": true,
              "cross_val_score": true,
              "smogn": false,
              "onnx": false,
              "backend": "loky",
              "n_jobs": 8,
              "num_inst": 10,
              "fpi_corr_cutoff": 50
            }
          }' --name "modex-iteration-cloud-pw" > pw-workflow-run.log
      - name: Wait for workflow completion
        # We need to wait for the workflow to complete, even though
        # it is NOT running on the GitHub runner because the short
        # term GITHUB_TOKEN used for authentication is valid only
        # during the lifetime of the workflow. In the future, for
        # very long running workflows, consider using SSH deploy
        # key authentication instead of GitHub tokens (max 6 hours).
        run: |
          echo Wait 10 s for workflow to start running on platform...
          sleep 10
          echo Set a flag...
          flag=1
          echo Get unique inline workflow name...
          slug=$(grep Slug pw-workflow-run.log | awk '{print $2}' )
          echo Checking for whether $slug is still running...
          # Check for at least one running workflow with
          # matching unique name
          while [ $flag -gt 0 ]; do
            echo Wait 5 seconds...
            sleep 5
            echo Counting number of workflows that match filters...
            flag=$( pw workflow runs ls | grep $slug | grep running | wc -l )
            echo Found ${flag} running ${slug} workflows.
          done
          echo "All instances of ${slug} have finished; workflow complete."
